/*
 * Odyssey.
 *
 * Scalable PostgreSQL connection pooler.
 */

#include <odyssey.h>

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <libgen.h>
#include <sys/stat.h>
#include <unistd.h>

#include <od_memory.h>
#include <util.h>
#include <cfg/reader.h>
#include <autoconf.h>

#define OD_AUTOCONF_HEADER                    \
	"# Do not edit this file manually!\n" \
	"# It is overwritten by ALTER SYSTEM.\n"

#define OD_AUTOCONF_COMMENT "# "

/* same characters as IDENT_CONT in cfg/scan.l */
static inline int od_autoconf_is_ident(char c)
{
	return isalnum((unsigned char)c) || c == '_';
}

/*
 * Whether a line (not including '\n') is an active option line, that
 * is neither empty nor a comment, and, when key is not NULL, whether
 * its first word is exactly key.
 */
static int od_autoconf_line_matches(const char *start, size_t len,
				    const char *key)
{
	const char *p = start;
	const char *end = start + len;

	while (p < end && (*p == ' ' || *p == '\t')) {
		p++;
	}
	if (p == end || *p == '#') {
		return 0;
	}
	if (key == NULL) {
		return 1;
	}

	size_t key_len = strlen(key);
	if ((size_t)(end - p) < key_len || strncmp(p, key, key_len) != 0) {
		return 0;
	}
	/* "workers" must not match "workers_count" */
	p += key_len;
	return p == end || !od_autoconf_is_ident(*p);
}

char *od_autoconf_apply(const char *old_text, const char *key, const char *line)
{
	size_t old_len = strlen(old_text);
	size_t line_len = line ? strlen(line) : 0;

	/* upper bound: every line may get a comment prefix */
	size_t lines = 1;
	for (const char *p = old_text; *p; p++) {
		if (*p == '\n') {
			lines++;
		}
	}
	size_t size = sizeof(OD_AUTOCONF_HEADER) + old_len +
		      lines * (sizeof(OD_AUTOCONF_COMMENT) - 1) + line_len +
		      2 /* '\n' before and after line */ + 1;

	char *out = od_malloc(size);
	if (out == NULL) {
		return NULL;
	}
	char *pos = out;

	if (old_len == 0) {
		memcpy(pos, OD_AUTOCONF_HEADER, sizeof(OD_AUTOCONF_HEADER) - 1);
		pos += sizeof(OD_AUTOCONF_HEADER) - 1;
	}

	const char *p = old_text;
	while (*p) {
		const char *nl = strchr(p, '\n');
		size_t len = nl ? (size_t)(nl - p) : strlen(p);

		if (od_autoconf_line_matches(p, len, key)) {
			memcpy(pos, OD_AUTOCONF_COMMENT,
			       sizeof(OD_AUTOCONF_COMMENT) - 1);
			pos += sizeof(OD_AUTOCONF_COMMENT) - 1;
		}
		memcpy(pos, p, len);
		pos += len;
		/* the last line may lack '\n', the result always ends with one */
		*pos++ = '\n';

		p += len;
		if (*p == '\n') {
			p++;
		}
	}

	if (line != NULL) {
		memcpy(pos, line, line_len);
		pos += line_len;
		*pos++ = '\n';
	}

	*pos = '\0';
	return out;
}

/* a missing file reads as an empty text */
static int od_autoconf_read(const char *path, char **text, char *err,
			    size_t err_size)
{
	*text = NULL;

	int fd = open(path, O_RDONLY | O_CLOEXEC);
	if (fd == -1) {
		if (errno != ENOENT) {
			od_snprintf(err, (int)err_size,
				    "could not open \"%s\": %s", path,
				    strerror(errno));
			return -1;
		}
		*text = od_strdup("");
		if (*text == NULL) {
			od_snprintf(err, (int)err_size, "out of memory");
			return -1;
		}
		return 0;
	}

	struct stat st;
	if (fstat(fd, &st) != 0) {
		od_snprintf(err, (int)err_size, "could not stat \"%s\": %s",
			    path, strerror(errno));
		close(fd);
		return -1;
	}
	if (st.st_size > OD_AUTOCONF_MAX_SIZE) {
		od_snprintf(err, (int)err_size,
			    "autoconf file \"%s\" is too large (limit is "
			    "%d bytes), remove old commented lines from "
			    "it by hand",
			    path, OD_AUTOCONF_MAX_SIZE);
		close(fd);
		return -1;
	}

	size_t size = (size_t)st.st_size;
	char *buf = od_malloc(size + 1);
	if (buf == NULL) {
		od_snprintf(err, (int)err_size, "out of memory");
		close(fd);
		return -1;
	}

	size_t done = 0;
	while (done < size) {
		ssize_t rc = read(fd, buf + done, size - done);
		if (rc < 0) {
			if (errno == EINTR) {
				continue;
			}
			od_snprintf(err, (int)err_size,
				    "could not read \"%s\": %s", path,
				    strerror(errno));
			od_free(buf);
			close(fd);
			return -1;
		}
		if (rc == 0) {
			/* the file got shorter since fstat() */
			break;
		}
		done += (size_t)rc;
	}
	buf[done] = '\0';
	close(fd);

	*text = buf;
	return 0;
}

static int od_autoconf_write_file(const char *path, const char *text, char *err,
				  size_t err_size)
{
	int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0600);
	if (fd == -1) {
		od_snprintf(err, (int)err_size, "could not create \"%s\": %s",
			    path, strerror(errno));
		return -1;
	}

	size_t len = strlen(text);
	size_t done = 0;
	while (done < len) {
		ssize_t rc = write(fd, text + done, len - done);
		if (rc < 0) {
			if (errno == EINTR) {
				continue;
			}
			od_snprintf(err, (int)err_size,
				    "could not write \"%s\": %s", path,
				    strerror(errno));
			close(fd);
			return -1;
		}
		done += (size_t)rc;
	}

	/* the data must be on disk before rename() makes it visible */
	if (fsync(fd) != 0) {
		od_snprintf(err, (int)err_size, "could not fsync \"%s\": %s",
			    path, strerror(errno));
		close(fd);
		return -1;
	}
	if (close(fd) != 0) {
		od_snprintf(err, (int)err_size, "could not close \"%s\": %s",
			    path, strerror(errno));
		return -1;
	}
	return 0;
}

/* makes a completed rename() durable */
static int od_autoconf_fsync_dir(const char *path, char *err, size_t err_size)
{
	/* dirname() may modify its argument */
	char *copy = od_strdup(path);
	if (copy == NULL) {
		od_snprintf(err, (int)err_size, "out of memory");
		return -1;
	}
	const char *dir = dirname(copy);

	int rc = -1;
	int fd = open(dir, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
	if (fd == -1) {
		od_snprintf(err, (int)err_size, "could not open \"%s\": %s",
			    dir, strerror(errno));
		goto cleanup;
	}
	if (fsync(fd) != 0) {
		od_snprintf(err, (int)err_size, "could not fsync \"%s\": %s",
			    dir, strerror(errno));
		close(fd);
		goto cleanup;
	}
	close(fd);
	rc = 0;

cleanup:
	od_free(copy);
	return rc;
}

/* the file must parse exactly as od_cfg_try_autoconf() will read it */
static int od_autoconf_validate(const char *path, char *err, size_t err_size)
{
	od_cfg_model_t model;
	od_cfg_diag_list_t diags;
	od_cfg_model_init(&model);
	od_cfg_diag_list_init(&diags);

	int rc = od_cfg_parse_autoconf(path, &model, &diags);
	if (rc != 0 || od_cfg_diag_has_errors(&diags)) {
		const od_cfg_diag_t *first = NULL;
		for (size_t i = 0; i < diags.count; i++) {
			if (diags.items[i].level == OD_CFG_DIAG_ERROR) {
				first = &diags.items[i];
				break;
			}
		}
		if (first != NULL) {
			od_snprintf(err, (int)err_size,
				    "invalid autoconf content at line %d: %s",
				    first->location.first_line,
				    first->message ? first->message : "");
		} else {
			od_snprintf(err, (int)err_size,
				    "invalid autoconf content");
		}
		rc = -1;
	}

	od_cfg_diag_list_free(&diags);
	od_cfg_model_free(&model);
	return rc;
}

int od_autoconf_update(const char *config_path, const char *key,
		       const char *line, od_autoconf_check_cb check,
		       void *check_arg, char *err, size_t err_size)
{
	char *path = NULL;
	char *tmp = NULL;
	char *old_text = NULL;
	char *new_text = NULL;
	int tmp_created = 0;
	int rc = -1;

	if (od_asprintf(&path, "%s%s", config_path, OD_CFG_AUTOCONF_SUFFIX) !=
		    OK_RESPONSE ||
	    od_asprintf(&tmp, "%s.tmp", path) != OK_RESPONSE) {
		od_snprintf(err, (int)err_size, "out of memory");
		goto cleanup;
	}

	if (od_autoconf_read(path, &old_text, err, err_size) != 0) {
		goto cleanup;
	}

	new_text = od_autoconf_apply(old_text, key, line);
	if (new_text == NULL) {
		od_snprintf(err, (int)err_size, "out of memory");
		goto cleanup;
	}
	if (strlen(new_text) > OD_AUTOCONF_MAX_SIZE) {
		od_snprintf(err, (int)err_size,
			    "autoconf file \"%s\" would exceed %d bytes, "
			    "remove old commented lines from it by hand",
			    path, OD_AUTOCONF_MAX_SIZE);
		goto cleanup;
	}

	/* the old file is not touched until the new one is complete */
	tmp_created = 1;
	if (od_autoconf_write_file(tmp, new_text, err, err_size) != 0) {
		goto cleanup;
	}
	if (od_autoconf_validate(tmp, err, err_size) != 0) {
		goto cleanup;
	}
	if (check != NULL && check(tmp, check_arg) != 0) {
		od_snprintf(err, (int)err_size,
			    "the configuration with this change is invalid, "
			    "see the odyssey log for details");
		goto cleanup;
	}
	if (rename(tmp, path) != 0) {
		od_snprintf(err, (int)err_size,
			    "could not rename \"%s\" to \"%s\": %s", tmp, path,
			    strerror(errno));
		goto cleanup;
	}
	tmp_created = 0;

	if (od_autoconf_fsync_dir(path, err, err_size) != 0) {
		goto cleanup;
	}
	rc = 0;

cleanup:
	if (tmp_created) {
		unlink(tmp);
	}
	od_free(new_text);
	od_free(old_text);
	od_free(tmp);
	od_free(path);
	return rc;
}
