#include <odyssey.h>
#include <tests/odyssey_test.h>

#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

#include <od_memory.h>
#include <autoconf.h>

#define HEADER                                \
	"# Do not edit this file manually!\n" \
	"# It is overwritten by ALTER SYSTEM.\n"

static void apply_ok(const char *old_text, const char *key, const char *line,
		     const char *expected)
{
	char *result = od_autoconf_apply(old_text, key, line);
	test(result != NULL);
	if (strcmp(result, expected) != 0) {
		fprintf(stderr,
			"apply_ok failed: key=[%s] line=[%s]\n"
			"--- old:\n%s\n--- expected:\n%s\n--- got:\n%s\n",
			key ? key : "(null)", line ? line : "(null)", old_text,
			expected, result);
		abort();
	}
	od_free(result);
}

static void test_autoconf_set_empty(void)
{
	apply_ok("", "workers", "workers 4", HEADER "workers 4\n");
}

static void test_autoconf_set_replaces(void)
{
	apply_ok("workers 4\n", "workers", "workers 8",
		 "# workers 4\n"
		 "workers 8\n");
}

static void test_autoconf_set_keeps_history(void)
{
	apply_ok(HEADER "# workers 4\n"
			"workers 8\n",
		 "workers", "workers 16",
		 HEADER "# workers 4\n"
			"# workers 8\n"
			"workers 16\n");
}

static void test_autoconf_set_keeps_other_keys(void)
{
	apply_ok("log_debug yes\n"
		 "workers 4\n"
		 "availability_zone \"b\"\n",
		 "workers", "workers 8",
		 "log_debug yes\n"
		 "# workers 4\n"
		 "availability_zone \"b\"\n"
		 "workers 8\n");
}

static void test_autoconf_set_key_prefix(void)
{
	apply_ok("workers_count 4\n", "workers", "workers 8",
		 "workers_count 4\n"
		 "workers 8\n");
	apply_ok("worker 4\n", "workers", "workers 8",
		 "worker 4\n"
		 "workers 8\n");
	/* the key is the whole first word, not a prefix of the line */
	apply_ok("workers\"4\"\n", "workers", "workers 8",
		 "# workers\"4\"\n"
		 "workers 8\n");
}

static void test_autoconf_set_leading_whitespace(void)
{
	apply_ok("  workers 4\n"
		 "\tworkers 5\n",
		 "workers", "workers 8",
		 "#   workers 4\n"
		 "# \tworkers 5\n"
		 "workers 8\n");
}

static void test_autoconf_set_inline_comment(void)
{
	apply_ok("workers 4 # old\n", "workers", "workers 8",
		 "# workers 4 # old\n"
		 "workers 8\n");
}

static void test_autoconf_set_duplicates(void)
{
	apply_ok("workers 4\n"
		 "log_debug yes\n"
		 "workers 5\n",
		 "workers", "workers 8",
		 "# workers 4\n"
		 "log_debug yes\n"
		 "# workers 5\n"
		 "workers 8\n");
}

static void test_autoconf_set_no_trailing_newline(void)
{
	apply_ok("workers 4", "workers", "workers 8",
		 "# workers 4\n"
		 "workers 8\n");
	apply_ok("log_debug yes", "workers", "workers 8",
		 "log_debug yes\n"
		 "workers 8\n");
}

static void test_autoconf_keeps_comments_and_blank_lines(void)
{
	apply_ok("# workers 4\n"
		 "\n"
		 "   # workers 5\n"
		 "\n",
		 "workers", "workers 8",
		 "# workers 4\n"
		 "\n"
		 "   # workers 5\n"
		 "\n"
		 "workers 8\n");
}

static void test_autoconf_reset(void)
{
	apply_ok("workers 4\n"
		 "log_debug yes\n",
		 "workers", NULL,
		 "# workers 4\n"
		 "log_debug yes\n");
	/* resetting an absent key leaves the text intact */
	apply_ok("log_debug yes\n", "workers", NULL, "log_debug yes\n");
	apply_ok("", "workers", NULL, HEADER);
}

static void test_autoconf_reset_all(void)
{
	apply_ok("# hdr\n"
		 "workers 4\n"
		 "\n"
		 "  log_debug yes\n"
		 "# workers 2\n",
		 NULL, NULL,
		 "# hdr\n"
		 "# workers 4\n"
		 "\n"
		 "#   log_debug yes\n"
		 "# workers 2\n");
	apply_ok("", NULL, NULL, HEADER);
}

static void test_autoconf_repeated_changes(void)
{
	char *text = od_autoconf_apply("", "workers", "workers 4");
	test(text != NULL);

	char *next = od_autoconf_apply(text, "log_debug", "log_debug yes");
	test(next != NULL);
	od_free(text);
	text = next;

	next = od_autoconf_apply(text, "workers", "workers 8");
	test(next != NULL);
	od_free(text);
	text = next;

	next = od_autoconf_apply(text, NULL, NULL);
	test(next != NULL);
	od_free(text);
	text = next;

	test(strcmp(text, HEADER "# workers 4\n"
				 "# log_debug yes\n"
				 "# workers 8\n") == 0);
	od_free(text);
}

/*
 * On-disk tests work in a fresh directory under /tmp. The main config
 * itself is never read, only <dir>/odyssey.conf.autoconf is touched.
 */
typedef struct {
	char dir[64];
	char config[128];
	char autoconf[160];
	char tmp[176];
} disk_env_t;

static void disk_env_init(disk_env_t *env)
{
	snprintf(env->dir, sizeof(env->dir),
		 "/tmp/odyssey_test_autoconf_XXXXXX");
	test(mkdtemp(env->dir) != NULL);
	snprintf(env->config, sizeof(env->config), "%s/odyssey.conf", env->dir);
	snprintf(env->autoconf, sizeof(env->autoconf), "%s.autoconf",
		 env->config);
	snprintf(env->tmp, sizeof(env->tmp), "%s.tmp", env->autoconf);
}

static void disk_env_free(disk_env_t *env)
{
	unlink(env->tmp);
	unlink(env->autoconf);
	test(rmdir(env->dir) == 0);
}

static void write_whole(const char *path, const char *text, size_t len)
{
	int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
	test(fd != -1);
	test(write(fd, text, len) == (ssize_t)len);
	test(close(fd) == 0);
}

/* returns od_malloc'ed contents */
static char *read_whole(const char *path)
{
	static char buf[4096];
	int fd = open(path, O_RDONLY);
	test(fd != -1);
	ssize_t n = read(fd, buf, sizeof(buf) - 1);
	test(n >= 0);
	test(close(fd) == 0);
	buf[n] = '\0';
	return od_strdup(buf);
}

static void expect_file(const char *path, const char *expected)
{
	char *text = read_whole(path);
	if (strcmp(text, expected) != 0) {
		fprintf(stderr,
			"expect_file failed: %s\n--- expected:\n%s\n--- got:\n%s\n",
			path, expected, text);
		abort();
	}
	od_free(text);
}

static void update_ok(disk_env_t *env, const char *key, const char *line)
{
	char err[256] = { 0 };
	int rc = od_autoconf_update(env->config, key, line, NULL, NULL, err,
				    sizeof(err));
	if (rc != 0) {
		fprintf(stderr,
			"update_ok failed: key=[%s] line=[%s] err=[%s]\n",
			key ? key : "(null)", line ? line : "(null)", err);
		abort();
	}
	test(access(env->tmp, F_OK) != 0);
}

static void update_fail(disk_env_t *env, const char *key, const char *line,
			const char *err_part)
{
	char err[256] = { 0 };
	int rc = od_autoconf_update(env->config, key, line, NULL, NULL, err,
				    sizeof(err));
	if (rc != -1 || strstr(err, err_part) == NULL) {
		fprintf(stderr,
			"update_fail failed: key=[%s] line=[%s] rc=%d err=[%s], "
			"expected [%s] in err\n",
			key ? key : "(null)", line ? line : "(null)", rc, err,
			err_part);
		abort();
	}
	/* a failed update never leaves the temporary file behind */
	test(access(env->tmp, F_OK) != 0);
}

static void test_autoconf_update_creates_file(void)
{
	disk_env_t env;
	disk_env_init(&env);

	test(access(env.autoconf, F_OK) != 0);
	update_ok(&env, "workers", "workers 4");
	expect_file(env.autoconf, HEADER "workers 4\n");

	struct stat st;
	test(stat(env.autoconf, &st) == 0);
	test((st.st_mode & 0777) == 0600);

	disk_env_free(&env);
}

static void test_autoconf_update_sequence(void)
{
	disk_env_t env;
	disk_env_init(&env);

	update_ok(&env, "workers", "workers 4");
	update_ok(&env, "availability_zone", "availability_zone \"a\\\"b\"");
	update_ok(&env, "workers", "workers 8");
	expect_file(env.autoconf, HEADER "# workers 4\n"
					 "availability_zone \"a\\\"b\"\n"
					 "workers 8\n");

	update_ok(&env, "workers", NULL);
	expect_file(env.autoconf, HEADER "# workers 4\n"
					 "availability_zone \"a\\\"b\"\n"
					 "# workers 8\n");

	update_ok(&env, NULL, NULL);
	expect_file(env.autoconf, HEADER "# workers 4\n"
					 "# availability_zone \"a\\\"b\"\n"
					 "# workers 8\n");

	disk_env_free(&env);
}

static void test_autoconf_update_invalid_keeps_file(void)
{
	disk_env_t env;
	disk_env_init(&env);

	update_ok(&env, "workers", "workers 4");

	/* rejected by the configuration parser */
	update_fail(&env, "workers", "workers abc", "invalid autoconf content");
	update_fail(&env, "include", "include \"/etc/passwd\"",
		    "invalid autoconf content");
	update_fail(&env, "no_such_option", "no_such_option 1",
		    "invalid autoconf content");

	expect_file(env.autoconf, HEADER "workers 4\n");

	disk_env_free(&env);
}

static void test_autoconf_update_too_large(void)
{
	disk_env_t env;
	disk_env_init(&env);

	/* a file already over the limit is not touched */
	size_t len = OD_AUTOCONF_MAX_SIZE + 1;
	char *big = od_malloc(len);
	test(big != NULL);
	memset(big, '#', len);
	write_whole(env.autoconf, big, len);

	update_fail(&env, "workers", "workers 4", "too large");

	struct stat st;
	test(stat(env.autoconf, &st) == 0);
	test((size_t)st.st_size == len);

	/* a file just under the limit cannot grow past it */
	memset(big, '#', len);
	big[OD_AUTOCONF_MAX_SIZE - 2] = '\n';
	write_whole(env.autoconf, big, OD_AUTOCONF_MAX_SIZE - 1);
	update_fail(&env, "workers", "workers 4", "would exceed");

	od_free(big);
	disk_env_free(&env);
}

typedef struct {
	int calls;
	int result;
	char seen[4096];
} check_state_t;

/* records what the check saw: the candidate file, not the current one */
static int check_record(const char *autoconf_path, void *arg)
{
	check_state_t *state = arg;
	state->calls++;
	char *text = read_whole(autoconf_path);
	snprintf(state->seen, sizeof(state->seen), "%s", text);
	od_free(text);
	return state->result;
}

static void test_autoconf_update_check(void)
{
	disk_env_t env;
	disk_env_init(&env);

	update_ok(&env, "workers", "workers 4");

	/* the check sees the new text in the temporary file */
	check_state_t state = { .calls = 0, .result = 0 };
	char err[256] = { 0 };
	test(od_autoconf_update(env.config, "workers", "workers 8",
				check_record, &state, err, sizeof(err)) == 0);
	test(state.calls == 1);
	test(strcmp(state.seen, HEADER "# workers 4\n"
				       "workers 8\n") == 0);
	expect_file(env.autoconf, HEADER "# workers 4\n"
					 "workers 8\n");

	/* a rejected check keeps the old file and removes the temporary one */
	state.calls = 0;
	state.result = -1;
	test(od_autoconf_update(env.config, "workers", "workers 1",
				check_record, &state, err, sizeof(err)) == -1);
	test(state.calls == 1);
	test(strstr(err, "configuration with this change is invalid") != NULL);
	test(access(env.tmp, F_OK) != 0);
	expect_file(env.autoconf, HEADER "# workers 4\n"
					 "workers 8\n");

	/* the parser runs first: a check never sees an unparsable file */
	state.calls = 0;
	update_fail(&env, "workers", "workers abc", "invalid autoconf content");
	test(state.calls == 0);

	disk_env_free(&env);
}

static void test_autoconf_update_missing_dir(void)
{
	char err[256] = { 0 };
	int rc = od_autoconf_update(
		"/tmp/odyssey_test_autoconf_no_such_dir/odyssey.conf",
		"workers", "workers 4", NULL, NULL, err, sizeof(err));
	test(rc == -1);
	test(strstr(err, "could not create") != NULL);
}

void odyssey_test_autoconf(void)
{
	test_autoconf_set_empty();
	test_autoconf_set_replaces();
	test_autoconf_set_keeps_history();
	test_autoconf_set_keeps_other_keys();
	test_autoconf_set_key_prefix();
	test_autoconf_set_leading_whitespace();
	test_autoconf_set_inline_comment();
	test_autoconf_set_duplicates();
	test_autoconf_set_no_trailing_newline();
	test_autoconf_keeps_comments_and_blank_lines();
	test_autoconf_reset();
	test_autoconf_reset_all();
	test_autoconf_repeated_changes();

	test_autoconf_update_creates_file();
	test_autoconf_update_sequence();
	test_autoconf_update_invalid_keeps_file();
	test_autoconf_update_too_large();
	test_autoconf_update_missing_dir();
	test_autoconf_update_check();
}
