all:
	@(cd machinarium; make --no-print-directory)
	@(cd soprano; make --no-print-directory)
clean:
	@(cd machinarium; make --no-print-directory clean)
	@(cd soprano; make --no-print-directory clean)
