pid_file "/tmp/odyssey.pid"
daemonize yes

log_format "%p %t %l [%i %s] (%c) %m\n"

log_to_stdout no

log_syslog no
log_syslog_ident "odyssey"
log_syslog_facility "daemon"

log_debug yes
log_config yes
log_session no
log_query no
log_stats no
log_file "/tmp/odyssey.log"
stats_interval 60

# cpu_affinity yes
workers 1
resolvers 1

readahead 4096

cache_coroutine 0

coroutine_stack_size 16

nodelay yes

keepalive 15
keepalive_keep_interval 75
keepalive_probes 9

keepalive_usr_timeout 0

listen {
	host "*"
	port 6432
	backlog 128
	compression yes
	tls "disable"
}

storage "postgres_server" {
	type "remote"
	host "localhost:5432"
	endpoints_status_poll_interval 100
}

database default {
	user default {
		authentication "none"

		# password "md588cb17a149f659b9a78ec4a33cbb3c7f"

		storage "postgres_server"
		pool "transaction"
		pool_size 32

#		auth_query "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
#		auth_query_db "postgres"
#		auth_query_user "reshke"
#		storage_password "reshke"

		pool_timeout 0

		pool_ttl 1201

		pool_discard yes

		pool_cancel yes

		pool_rollback yes
		pool_reserve_prepared_statement yes
#		seconds
		pool_client_idle_timeout 20000
#		seconds
		pool_idle_in_transaction_timeout 20000

		client_fwd_error yes
		application_name_add_host no
		server_lifetime 1901
		log_debug no

		# quantiles "0.99,0.95,0.5"
		client_max 200000
	}
}

storage "local" {
	type "local"
}

database "console" {
	user default {
		authentication "none"
		role "admin"
		pool "session"
		storage "local"
	}
}


locks_dir "/tmp/odyssey"

graceful_die_on_errors yes
enable_online_restart no
bindwith_reuseport yes