services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - od_jemalloc_test_net

  runner:
    init: true
    build:
      dockerfile: ./docker/jemalloc/Dockerfile
      context: ../../ # odyssey root dir
      args:
        odyssey_build_type: "${ODYSSEY_JEMALLOC_TEST_BUILD_TYPE:-build_release}"
    ports:
      - "6432:6432"
    networks:
      - od_jemalloc_test_net

networks:
  od_jemalloc_test_net:
    driver: bridge
