/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include <sql/full/kwlookup.h>

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compression\0"
	"concurrently\0"
	"conditional\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"else\0"
	"empty\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enforced\0"
	"enum\0"
	"error\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_exists\0"
	"json_object\0"
	"json_objectagg\0"
	"json_query\0"
	"json_scalar\0"
	"json_serialize\0"
	"json_table\0"
	"json_value\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"lsn\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"merge_action\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"nested\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"none\0"
	"normalize\0"
	"normalized\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"object\0"
	"objects\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"omit\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"parallel\0"
	"parameter\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"path\0"
	"period\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"quotes\0"
	"range\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repack\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"respect\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"sql\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"string\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unconditional\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"volatile\0"
	"wait\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	36,
	40,
	46,
	52,
	62,
	66,
	71,
	77,
	84,
	92,
	100,
	104,
	108,
	114,
	117,
	121,
	132,
	142,
	153,
	164,
	167,
	174,
	181,
	191,
	205,
	214,
	221,
	227,
	235,
	242,
	249,
	253,
	261,
	266,
	274,
	277,
	283,
	288,
	295,
	303,
	312,
	317,
	322,
	330,
	336,
	341,
	351,
	367,
	373,
	384,
	390,
	396,
	404,
	413,
	421,
	431,
	438,
	446,
	454,
	463,
	470,
	480,
	492,
	505,
	517,
	531,
	540,
	551,
	562,
	574,
	582,
	591,
	602,
	607,
	612,
	619,
	625,
	629,
	634,
	642,
	658,
	671,
	684,
	699,
	712,
	730,
	743,
	750,
	756,
	761,
	770,
	774,
	785,
	789,
	797,
	805,
	813,
	822,
	833,
	842,
	850,
	857,
	867,
	878,
	886,
	892,
	897,
	904,
	915,
	923,
	931,
	940,
	943,
	952,
	959,
	966,
	971,
	976,
	981,
	987,
	994,
	1003,
	1013,
	1017,
	1026,
	1031,
	1037,
	1044,
	1050,
	1057,
	1065,
	1075,
	1085,
	1093,
	1100,
	1108,
	1119,
	1129,
	1138,
	1146,
	1152,
	1159,
	1165,
	1172,
	1181,
	1187,
	1193,
	1203,
	1207,
	1213,
	1221,
	1228,
	1236,
	1243,
	1248,
	1253,
	1262,
	1272,
	1282,
	1289,
	1295,
	1303,
	1312,
	1318,
	1327,
	1334,
	1342,
	1349,
	1356,
	1361,
	1366,
	1375,
	1378,
	1385,
	1391,
	1401,
	1411,
	1420,
	1427,
	1430,
	1438,
	1448,
	1458,
	1465,
	1471,
	1479,
	1487,
	1496,
	1506,
	1513,
	1519,
	1525,
	1531,
	1543,
	1550,
	1558,
	1562,
	1570,
	1580,
	1589,
	1594,
	1602,
	1605,
	1612,
	1622,
	1627,
	1632,
	1643,
	1657,
	1669,
	1681,
	1696,
	1707,
	1719,
	1734,
	1745,
	1756,
	1761,
	1765,
	1770,
	1776,
	1785,
	1791,
	1796,
	1804,
	1812,
	1822,
	1828,
	1833,
	1839,
	1844,
	1850,
	1857,
	1862,
	1868,
	1878,
	1893,
	1902,
	1907,
	1914,
	1921,
	1925,
	1933,
	1939,
	1947,
	1960,
	1969,
	1975,
	1988,
	1995,
	2002,
	2011,
	2016,
	2022,
	2027,
	2032,
	2038,
	2047,
	2055,
	2061,
	2068,
	2072,
	2077,
	2081,
	2085,
	2090,
	2095,
	2098,
	2103,
	2113,
	2124,
	2128,
	2136,
	2143,
	2151,
	2158,
	2163,
	2170,
	2176,
	2184,
	2191,
	2199,
	2202,
	2206,
	2213,
	2218,
	2222,
	2227,
	2230,
	2235,
	2244,
	2251,
	2259,
	2262,
	2268,
	2279,
	2286,
	2290,
	2296,
	2301,
	2310,
	2318,
	2329,
	2335,
	2341,
	2350,
	2360,
	2367,
	2375,
	2385,
	2393,
	2402,
	2407,
	2414,
	2422,
	2427,
	2433,
	2440,
	2449,
	2459,
	2469,
	2477,
	2486,
	2495,
	2503,
	2509,
	2520,
	2531,
	2541,
	2552,
	2560,
	2572,
	2578,
	2585,
	2591,
	2596,
	2601,
	2610,
	2620,
	2624,
	2635,
	2647,
	2655,
	2663,
	2672,
	2680,
	2687,
	2694,
	2705,
	2713,
	2721,
	2727,
	2735,
	2743,
	2752,
	2759,
	2769,
	2777,
	2784,
	2790,
	2795,
	2804,
	2811,
	2819,
	2828,
	2832,
	2837,
	2842,
	2852,
	2859,
	2866,
	2874,
	2881,
	2888,
	2895,
	2904,
	2911,
	2920,
	2930,
	2943,
	2950,
	2958,
	2971,
	2975,
	2981,
	2986,
	2992,
	2997,
	3005,
	3012,
	3017,
	3026,
	3035,
	3040,
	3047,
	3051,
	3058,
	3069,
	3075,
	3085,
	3096,
	3102,
	3109,
	3117,
	3124,
	3131,
	3138,
	3144,
	3157,
	3167,
	3175,
	3185,
	3191,
	3198,
	3210,
	3216,
	3223,
	3235,
	3246,
	3253,
	3258,
	3267,
	3277,
	3282,
	3287,
	3292,
	3297,
	3307,
	3310,
	3319,
	3331,
	3341,
	3347,
	3355,
	3360,
	3365,
	3374,
	3382,
	3387,
	3393,
	3401,
	3411,
	3423,
	3437,
	3449,
	3455,
	3462,
	3470,
	3479,
	3488,
	3494,
	3501,
	3506,
	3512,
	3519,
	3525,
	3534,
	3544,
	3550,
	3557,
	3565,
	3574,
	3582,
	3590,
	3598,
	3603,
	3609,
	3617,
	3626,
	3631,
	3636,
	3642,
	3653,
	3660,
	3665,
	3672,
	3680,
	3685,
	3693,
	3699,
	3703,
	3717,
	3727,
	3738,
	3748,
	3758,
	3772,
	3781,
	3787,
	3795,
	3808,
	3817,
	3822,
	3826,
};

#define SCANKEYWORDS_NUM_KEYWORDS 500

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[999] = {
		347,   331,   180,   3,     283,   32767, 32767, 147,
		32767, 32767, 32767, -6,    32767, 37,    32767, 32767,
		32767, -200,  32767, 47,    -390,  -254,  -56,   490,
		777,   -215,  458,   -45,   677,   0,     179,   32767,
		32767, 32767, 32767, -35,   -345,  -307,  0,     66,
		20,    209,   167,   498,   32767, 0,     0,     0,
		32767, 1148,  0,     -451,  32767, 32767, 32767, -360,
		749,   234,   -954,  24,    -108,  32767, 0,     0,
		32767, 32767, 0,     -22,   304,   21,    -269,  -117,
		32767, 319,   270,   32767, 753,   -107,  583,   276,
		32767, 32767, 0,     1093,  98,    0,     32767, 253,
		32767, 32767, 32767, 1294,  434,   461,   32767, 0,
		788,   -1026, -19,   81,    32767, 167,   0,     0,
		32767, 32767, -465,  -308,  0,     32767, 32767, 0,
		32767, 896,   176,   32767, 32767, 32767, 195,   32767,
		0,     32767, 183,   32767, 419,   -662,  -108,  -848,
		32767, 181,   -656,  32767, 475,   562,   32767, 439,
		450,   -247,  284,   0,     -622,  368,   -91,   0,
		32767, -242,  0,     -1035, 32767, 1112,  32767, 0,
		180,   1086,  -289,  -100,  161,   32767, 0,     32767,
		32767, 376,   32767, -742,  32767, 32767, -488,  175,
		32767, 1119,  14,    200,   32767, 32767, 32767, 906,
		218,   40,    32767, -605,  0,     32767, -559,  32767,
		356,   349,   415,   32767, 32767, 32767, -4,    32767,
		0,     100,   -764,  279,   32767, 59,    -316,  -153,
		38,    32767, 32767, 32767, 32767, 32767, 32767, 0,
		999,   65,    32767, -103,  32767, 431,   447,   32767,
		32767, 248,   354,   56,    32767, -75,   32767, 32767,
		32767, 832,   32767, 720,   229,   32767, -514,  32767,
		425,   -916,  32767, 32767, 32767, 32767, -902,  32767,
		-168,  108,   0,     32767, 379,   79,    401,   -290,
		32767, -311,  71,    32767, 32767, 32767, 32767, 32767,
		-304,  199,   32767, 32767, 32767, 104,   840,   32767,
		1439,  -160,  50,    32767, 32767, -532,  406,   -464,
		221,   32767, 46,    455,   32767, 32767, 0,     32767,
		187,   32767, 68,    32767, 69,    32767, -351,  32767,
		251,   -109,  32767, 162,   32767, -357,  -277,  32767,
		650,   -402,  32767, 180,   32767, 353,   32767, 102,
		32767, 364,   32767, -357,  -109,  32767, 32767, 490,
		0,     -518,  32767, 32767, -776,  32767, 94,    32767,
		0,     32767, 422,   342,   19,    0,     32767, 32767,
		-360,  72,    -664,  -133,  203,   32767, 275,   511,
		32767, 387,   32767, 322,   391,   470,   32767, 336,
		32767, 32767, 701,   32767, 32767, -33,   32767, 0,
		225,   0,     32767, 264,   446,   32767, 32767, -3,
		293,   0,     32767, 32767, 32767, 32767, 0,     473,
		32767, 32767, 32767, 491,   32767, 133,   32767, -259,
		-635,  -304,  32767, 32767, 32767, 32767, 32767, 49,
		194,   32767, 32767, 165,   32767, -31,   0,     32767,
		0,     32767, 32767, 32767, 175,   224,   32767, 32767,
		640,   32767, 114,   -633,  32767, 0,     -41,   287,
		170,   0,     32767, 29,    -391,  -517,  -880,  -961,
		224,   25,    -724,  0,     223,   -58,   0,     -172,
		32767, 475,   32767, 0,     32767, 298,   32767, 0,
		32767, 0,     32767, 250,   32767, 1414,  0,     32767,
		745,   32767, 0,     32767, 157,   0,     123,   32767,
		32767, 590,   32767, 358,   222,   -416,  32767, 32767,
		-470,  32767, 173,   32767, 75,    -689,  -295,  32767,
		32767, -118,  388,   32767, 0,     32767, 761,   141,
		-52,   875,   452,   32767, 0,     32767, 0,     32767,
		441,   272,   216,   495,   32767, 41,    381,   32767,
		519,   0,     32767, 32767, -253,  0,     37,    32767,
		498,   32767, 32767, -521,  646,   0,     32767, 0,
		32767, 87,    0,     32767, 0,     32767, 0,     32767,
		471,   700,   32767, 32767, 32767, 536,   0,     131,
		322,   47,    32767, 32767, 32767, 32767, 32767, 32767,
		977,   -17,   32767, 32767, 32767, 0,     32767, 504,
		-428,  373,   718,   32767, 342,   0,     32767, -119,
		170,   32767, 32767, 0,     0,     260,   32767, 32767,
		-239,  161,   32767, 0,     120,   32767, 0,     32767,
		189,   658,   32767, -9,    -164,  125,   32767, -747,
		999,   303,   361,   -600,  48,    0,     32767, 32767,
		383,   5,     32767, 32767, 0,     34,    32767, -651,
		0,     467,   46,    -284,  0,     -441,  32767, 424,
		342,   97,    32767, 32767, 0,     32767, 478,   0,
		290,   1029,  190,   -882,  0,     32767, 0,     32767,
		32767, 164,   32767, 0,     -147,  -188,  172,   32767,
		1078,  382,   32767, 32767, 32767, 32767, 0,     928,
		32767, 32767, -151,  542,   1076,  -41,   433,   0,
		690,   -519,  -254,  32767, 1432,  32767, 0,     963,
		573,   657,   0,     0,     761,   -498,  32767, 32767,
		1144,  32767, 32767, 32767, 32767, 0,     442,   455,
		32767, -153,  0,     32767, -265,  0,     416,   32767,
		280,   292,   32767, 32767, 143,   1332,  -995,  -50,
		0,     378,   471,   31,    32767, 32767, 0,     32767,
		32767, 41,    32767, 32767, 32767, -637,  32767, 0,
		328,   594,   35,    32767, 723,   123,   32767, 32767,
		32767, 86,    1173,  444,   32767, 32767, 0,     65,
		32767, 480,   -421,  32767, 277,   32767, 212,   -257,
		0,     0,     -601,  201,   32767, 32767, 118,   325,
		0,     302,   274,   32767, 191,   -1031, 408,   32767,
		-207,  198,   925,   451,   253,   378,   79,    32767,
		0,     0,     -7,    188,   46,    0,     -75,   32767,
		214,   32767, 32767, 1110,  32767, 0,     63,    35,
		32767, 228,   -1021, 32767, 0,     231,   323,   32767,
		1115,  32767, 163,   87,    265,   32767, 32767, 32767,
		-33,   32767, 32767, 0,     -257,  9,     119,   32767,
		-229,  361,   -194,  -17,   0,     754,   92,    -85,
		0,     32767, 32767, 215,   13,    32767, 699,   32767,
		-184,  460,   32767, 246,   32767, 369,   0,     1176,
		32767, 0,     32767, 244,   32767, 113,   334,   32767,
		32767, 345,   389,   0,     -647,  -481,  32767, 32767,
		-499,  32767, 17,    42,    -411,  32767, -444,  207,
		32767, 32767, 32767, 32767, 32767, 32767, 0,     32767,
		-398,  32767, 32767, 740,   -938,  263,   0,     32767,
		32767, 32767, 32767, 135,   32767, 0,     148,   32767,
		32767, 234,   32767, 285,   32767, 459,   32767, 32767,
		32767, 522,   0,     229,   32767, 0,     -553,  32767,
		-295,  209,   543,   -994,  32767, 417,   32767, 32767,
		-927,  -608,  32767, 32767, 428,   -177,  357,   237,
		0,     185,   32767, 337,   194,   923,   -114,  32767,
		0,     33,    0,     816,   1037,  341,   0,     412,
		32767, 350,   763,   0,     407,   32767, -385,  0,
		551,   -385,  32767, 32767, 219,   32767, 0,     32767,
		431,   -293,  -17,   -48,   32767, 200,   32767, 96,
		0,     32767, 36,    -829,  224,   243,   269,   55,
		32767, -159,  32767, -67,   32767, 0,     32767, 494,
		32767, 32767, 0,     0,     32767, 462,   32767, 0,
		271,   32767, 32767, 0,     32767, 714,   32767, 32767,
		1054,  20,    497,   32767, 86,    0,     0,     0,
		-507,  202,   484,   32767, 32767, 32767, 237,   32767,
		-426,  319,   0,     -571,  32767, 32767, 105,   32767,
		428,   423,   -93,   32767, 32767, 32767, 32767, 0,
		32767, 34,    0,     412,   32767, 294,   32767, 5,
		301,   32767, 488,   371,   -294,  0,     667
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 3;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 8191 + c;
	}
	return h[a % 999] + h[b % 999];
}

extern PGDLLIMPORT const ScanKeywordList ScanKeywords;

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	17
};

#endif							/* KWLIST_D_H */
