#pragma once

#include <pg_compat.h>
#include <common/fe_memutils.h>

typedef enum NodeTag
{
	T_Invalid = 0,
	T_RawStmt,
	T_SelectStmt,
	T_InsertStmt,
	T_UpdateStmt,
	T_DeleteStmt,
	T_MergeStmt,
	T_ColumnRef,
	T_A_Const,
	T_A_Star,
	T_ResTarget,
	T_RangeVar,
	T_Alias,
	T_TypeName,
	T_String,
	T_BitString,
	T_Integer,
	T_Float,
	T_Boolean,
	T_Null,
	T_DefElem,
	T_A_Expr,
	T_A_ArrayExpr,
	T_RangeFunction,
	T_JoinExpr,
	T_SortBy,
	T_WindowDef,
	T_A_Indices,
	T_MergeWhenClause,
	T_FunctionCall,
	T_FuncCall,
	T_GroupingSet,
	T_VacuumRelation,
	T_CommonTableExpr,
	T_WithClause,
	T_InferClause,
	T_OnConflictClause,
	T_LockingClause,
	T_RowExpr,
	T_TypeCast,
	T_CaseExpr,
	T_CaseWhen,
	T_SubLink,
	T_MultiAssignRef,
	T_SetToDefault,
	T_CoalesceExpr,
	T_MinMaxExpr,
	T_SQLValueFunction,
	T_XmlExpr,
	T_XmlSerialize,
	T_BoolExpr,
	T_NullIfExpr,
	T_NullTest,
	T_Indirection,
	T_CollateClause,
	T_ErrorSaveContext,
	T_List,
	T_JsonBehavior,
	T_JsonTablePathSpec,
	T_JsonValueExpr,
	T_JsonFormat,
	T_IntList,
	T_ATAlterConstraint,
	T_A_Indirection,
	T_AccessPriv,
	T_AlterCollationStmt,
	T_AlterDatabaseRefreshCollStmt,
	T_AlterDatabaseSetStmt,
	T_AlterDatabaseStmt,
	T_AlterDefaultPrivilegesStmt,
	T_AlterDomainStmt,
	T_AlterEnumStmt,
	T_AlterEventTrigStmt,
	T_AlterExtensionContentsStmt,
	T_AlterExtensionStmt,
	T_AlterFdwStmt,
	T_AlterForeignServerStmt,
	T_AlterFunctionStmt,
	T_AlterObjectDependsStmt,
	T_AlterObjectSchemaStmt,
	T_AlterOpFamilyStmt,
	T_AlterOperatorStmt,
	T_AlterOwnerStmt,
	T_AlterPolicyStmt,
	T_AlterPublicationStmt,
	T_AlterRoleSetStmt,
	T_AlterRoleStmt,
	T_AlterSeqStmt,
	T_AlterStatsStmt,
	T_AlterSubscriptionStmt,
	T_AlterSystemStmt,
	T_AlterTSConfigurationStmt,
	T_AlterTSDictionaryStmt,
	T_AlterTableCmd,
	T_AlterTableMoveAllStmt,
	T_AlterTableSpaceOptionsStmt,
	T_AlterTableStmt,
	T_AlterTypeStmt,
	T_AlterUserMappingStmt,
	T_BooleanTest,
	T_CTECycleClause,
	T_CTESearchClause,
	T_CallStmt,
	T_CheckPointStmt,
	T_ClosePortalStmt,
	T_ColumnDef,
	T_CommentStmt,
	T_CompositeTypeStmt,
	T_Constraint,
	T_ConstraintsSetStmt,
	T_CopyStmt,
	T_CreateAmStmt,
	T_CreateCastStmt,
	T_CreateConversionStmt,
	T_CreateDomainStmt,
	T_CreateEnumStmt,
	T_CreateEventTrigStmt,
	T_CreateExtensionStmt,
	T_CreateFdwStmt,
	T_CreateForeignServerStmt,
	T_CreateForeignTableStmt,
	T_CreateFunctionStmt,
	T_CreateOpClassItem,
	T_CreateOpClassStmt,
	T_CreateOpFamilyStmt,
	T_CreatePLangStmt,
	T_CreatePolicyStmt,
	T_CreatePublicationStmt,
	T_CreateRangeStmt,
	T_CreateRoleStmt,
	T_CreateSchemaStmt,
	T_CreateSeqStmt,
	T_CreateStatsStmt,
	T_CreateStmt,
	T_CreateSubscriptionStmt,
	T_CreateTableAsStmt,
	T_CreateTableSpaceStmt,
	T_CreateTransformStmt,
	T_CreateTrigStmt,
	T_CreateUserMappingStmt,
	T_CreatedbStmt,
	T_CurrentOfExpr,
	T_DeallocateStmt,
	T_DeclareCursorStmt,
	T_DefineStmt,
	T_DiscardStmt,
	T_DoStmt,
	T_DropOwnedStmt,
	T_DropRoleStmt,
	T_DropStmt,
	T_DropSubscriptionStmt,
	T_DropTableSpaceStmt,
	T_DropUserMappingStmt,
	T_DropdbStmt,
	T_ExecuteStmt,
	T_ExplainStmt,
	T_FetchStmt,
	T_FunctionParameter,
	T_GrantRoleStmt,
	T_GrantStmt,
	T_GroupingFunc,
	T_ImportForeignSchemaStmt,
	T_IndexElem,
	T_IndexStmt,
	T_IntoClause,
	T_JsonAggConstructor,
	T_JsonArgument,
	T_JsonArrayAgg,
	T_JsonArrayConstructor,
	T_JsonArrayQueryConstructor,
	T_JsonFuncExpr,
	T_JsonObjectAgg,
	T_JsonObjectConstructor,
	T_JsonOutput,
	T_JsonParseExpr,
	T_JsonReturning,
	T_JsonScalarExpr,
	T_JsonSerializeExpr,
	T_JsonTable,
	T_JsonTableColumn,
	T_ListenStmt,
	T_LoadStmt,
	T_LockStmt,
	T_MergeSupportFunc,
	T_NamedArgExpr,
	T_NotifyStmt,
	T_ObjectWithArgs,
	T_PLAssignStmt,
	T_ParamRef,
	T_PartitionBoundSpec,
	T_PartitionCmd,
	T_PartitionElem,
	T_PartitionSpec,
	T_PrepareStmt,
	T_PublicationAllObjSpec,
	T_PublicationObjSpec,
	T_PublicationTable,
	T_RangeSubselect,
	T_RangeTableFunc,
	T_RangeTableFuncCol,
	T_RangeTableSample,
	T_ReassignOwnedStmt,
	T_RefreshMatViewStmt,
	T_ReindexStmt,
	T_RenameStmt,
	T_RepackStmt,
	T_ReplicaIdentityStmt,
	T_ReturnStmt,
	T_ReturningClause,
	T_ReturningOption,
	T_RoleSpec,
	T_RuleStmt,
	T_SecLabelStmt,
	T_StatsElem,
	T_TableLikeClause,
	T_TransactionStmt,
	T_TriggerTransition,
	T_TruncateStmt,
	T_UnlistenStmt,
	T_VacuumStmt,
	T_VariableSetStmt,
	T_VariableShowStmt,
	T_ViewStmt,
	T_WaitStmt,
} NodeTag;

typedef struct Node
{
	NodeTag type;
} Node;

#define nodeTag(nodeptr) (((const Node*)(nodeptr))->type)

#define IsA(nodeptr, _type_) (nodeTag(nodeptr) == T_##_type_)

#define castNode(_type_, obj) ((_type_ *) obj)

static inline Node *newNode(size_t size, NodeTag tag)
{
	Node *result = (Node *) palloc0(size);
	result->type = tag;
	return result;
}

#define makeNode(_type_) ((_type_ *) newNode(sizeof(_type_), T_##_type_))

#define pg_node_attr(...)

typedef int ParseLoc;

#define INVALID_PARSE_LOC (-1)
