name: Async notification proxy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "CMakeLists.txt"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
jobs:
  async-notification:
    name: async-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Test with async notifications against Odyssey
      run: make async-notice-test
