name: Jemalloc compatibility test tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "third_party/**"
      - "test/**"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
    paths-ignore:
      - "docker/prom-exporter/**"
jobs:
  jemalloc:
    name: Jemalloc compatibility test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ['build_release']
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Odyssey jemalloc compatibility tests
      run: make jemalloc-test ODYSSEY_BUILD_TYPE=${{ matrix.build-type }}
