name: Check log_max_msg_size feature
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/logger.c"
      - "sources/include/logger.h"
      - "test/log-max-msg-size/**"
jobs:
  log-max-msg-size:
    name: log-max-msg-size
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Check log_max_msg_size works
      run: make log-max-msg-size-test
