name: pg_regress tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "CMakeLists.txt"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
      - "!sources/machinarium/gdb/**"
jobs:
  build_pg_base:
    name: Build pg-base image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build pg-base Docker image
      run: make pg-base-image
    - name: Save pg-base image
      run: docker save odyssey/pg-base -o /tmp/pg-base.tar
    - uses: actions/upload-artifact@v4
      with:
        name: pg-base-image
        path: /tmp/pg-base.tar
        retention-days: 1

  regress_tests:
    name: pg_regress
    runs-on: ubuntu-latest
    needs: build_pg_base
    strategy:
      fail-fast: false
      matrix:
        build-type: ['build_release', 'build_asan', 'build_dbg']
        cc: ['clang', 'gcc']
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - uses: actions/download-artifact@v4
      with:
        name: pg-base-image
        path: /tmp
    - name: Load pg-base image
      run: docker load -i /tmp/pg-base.tar
    - name: Odyssey pg_regress tests
      run: make regress_test ODYSSEY_BUILD_TYPE=${{ matrix.build-type }} ODYSSEY_CC=${{ matrix.cc }}
