name: Protocol tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "CMakeLists.txt"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
jobs:
  protocol:
    name: protocol
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        build-type: ['build_release', 'build_asan', 'build_dbg']
        cc: ['clang', 'gcc']
        tag: ['simple', 'copy', 'xproto']
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Odyssey protocol tests
      run: make proto-test ODYSSEY_BUILD_TYPE=${{ matrix.build-type }} ODYSSEY_CC=${{ matrix.cc }} PROTO_TEST_TAG=${{ matrix.tag }}
