name: Protocol tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "sources/**"
      - "test/**"
      - "CMakeLists.txt"
      - "docker/**"
      - "modules/**"
      - "cmake/**"
      - "!docker/prom-exporter/**"
jobs:
  protocol-tests:
    name: protocol-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Odyssey pg protocol compatibility test
      run: make protocol_test
